# Generated by Django 3.2.25 on 2024-11-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('media_id', models.CharField(max_length=100)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Show'), ('anime', 'Anime'), ('manga', 'Manga'), ('book', 'Book')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('watching', 'Currently Watching'), ('plan_to_watch', 'Plan to Watch'), ('completed', 'Completed'), ('dropped', 'Dropped')], max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('total_episodes', models.IntegerField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
